### ISSUE TITLE
Delete checkpatch.pl

### ISSUE THREAD

**Issue by planetA** [yaoxinjing/simpleDeviceDriver#3]
Delete `checkpatch.pl`, because it is a tool supplied with the Linux kernel. It is not a part of your repository. Try to maintain only necessary files there.

**Comment by planetA** [comment]
And spelling.txt as well of course

**Comment by yaoxinjing** [comment]
okay, i don't know that before. i learned everything from a post online ,which told me that i should donwload those two file in order to use it. 

i have deleted thoes files totaly and use following commands to find the `checkpatch.pl` in linux kernel source tree
sudo wget -O /usr/bin/checkpatch.pl "https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl"
sudo wget -O /usr/bin/spelling.txt "https://raw.githubusercontent.com/torvalds/linux/master/scripts/spelling.txt"
sudo chmod 755 /usr/bin/checkpatch.pl

**Comment by planetA** [comment]
Do you have linux kernel source tree downloaded?

**Comment by yaoxinjing** [comment]
No, i mean ,i download the checkpatch.pl and spelling.txt according to the tip in visual code studio. after that i enable a extension called "checkpatch",which check the linux code style automaticly

**Comment by planetA** [comment]
You need to have the Linux kernel anyway, so I would just recommend using it from there. It is discouraged to install applications outside of package management control.

**Comment by yaoxinjing** [comment]
okay,thanks
